#!/bin/bash

SCRIPT_LOCATION="$(type -p ${0})"

if [[ -L "${SCRIPT_LOCATION}" ]]
then
    DDC_HOME="$(dirname $(readlink ${SCRIPT_LOCATION}))/"
else
    DDC_HOME="$(dirname ${SCRIPT_LOCATION})"
fi

CLASSPATH="${DDC_HOME}/../lib/*"

tty >/dev/null 2>&1 && stty -icanon min 1 -echo

java -cp "$CLASSPATH" com.tuneit.duckdebug.Main $@

tty >/dev/null 2>&1 && stty icanon echo